name: currency_converter
description: "Currency Converter App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

