name: currency_converter
description: "Currency Converter App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

