typedef Currency = ({String name, String symbol, String flag});

const Map<String, Currency> kCurrencies = {
  'USD': (name: 'US Dollar', symbol: '\$', flag: '🇺🇸'),
  'EUR': (name: 'Euro', symbol: '€', flag: '🇪🇺'),
  'GBP': (name: 'British Pound', symbol: '£', flag: '🇬🇧'),
  'JPY': (name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵'),
  'AUD': (name: 'Australian Dollar', symbol: 'A\$', flag: '🇦🇺'),
  'CAD': (name: 'Canadian Dollar', symbol: 'C\$', flag: '🇨🇦'),
  'CHF': (name: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭'),
  'CNY': (name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳'),
  'SEK': (name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪'),
  'NZD': (name: 'New Zealand Dollar', symbol: 'NZ\$', flag: '🇳🇿'),
  'MXN': (name: 'Mexican Peso', symbol: '\$', flag: '🇲🇽'),
  'SGD': (name: 'Singapore Dollar', symbol: 'S\$', flag: '🇸🇬'),
  'HKD': (name: 'Hong Kong Dollar', symbol: 'HK\$', flag: '🇭🇰'),
  'NOK': (name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴'),
  'KRW': (name: 'South Korean Won', symbol: '₩', flag: '🇰🇷'),
  'TRY': (name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷'),
  'RUB': (name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺'),
  'INR': (name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳'),
  'BRL': (name: 'Brazilian Real', symbol: 'R\$', flag: '🇧🇷'),
  'ZAR': (name: 'South African Rand', symbol: 'R', flag: '🇿🇦'),
  'DKK': (name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰'),
  'PLN': (name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱'),
  'THB': (name: 'Thai Baht', symbol: '฿', flag: '🇹🇭'),
  'IDR': (name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩'),
  'HUF': (name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺'),
  'CZK': (name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿'),
  'ILS': (name: 'Israeli Shekel', symbol: '₪', flag: '🇮🇱'),
  'CLP': (name: 'Chilean Peso', symbol: '\$', flag: '🇨🇱'),
  'PHP': (name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭'),
  'AED': (name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪'),
  'COP': (name: 'Colombian Peso', symbol: '\$', flag: '🇨🇴'),
  'SAR': (name: 'Saudi Riyal', symbol: '﷼', flag: '🇸🇦'),
  'MYR': (name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾'),
  'RON': (name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴'),
};